# Generated by Django 5.2.3 on 2025-08-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
